### ISSUE TITLE
Analog to input$myMap_click

### ISSUE THREAD

**Issue by mosscoder** [r-spatial/plainview#2]
Greetings, I'm working on a pixel painting Shiny app that I think would benefit greatly from plainview package: https://github.com/mosscoder/paint2train

The core functionality of the app allows the user to visualize imagery tiles, click on grid cells, label them from a list of classes, and then save a .tif with values corresponding to those classes for as training data in a machine learning pipeline. Right now it's rleaflet-based with some mapview package mixed in. The app is heavily dependent on the ability to extract coordinates from the leaflet map, which is inconvenient, because the output from input$myMap_click is in latlong, and it would be better to simply return a row and column, agnostic to CRS. 

It appears that plainview does this and reports row and column, but it is unclear how you might extract and store row/cols in an interactive shiny context. 

Is this possible?

**Comment by tim-salabim** [comment]
Good question. I think it is possible, but I don't have much experience with the javascript side of shiny functions. So you'd want a return value that holds row/col coordinates of the click right?

**Comment by mosscoder** [comment]
Yes, that's what I'd need.

**Comment by mosscoder** [comment]
Or, simply the row and column index

**Comment by tim-salabim** [comment]
So, the following works. But I fear there's lots more to sort out (apart from click events) before plainview is usable in a shiny context... 

```r
library(shiny)
library(plainview)

plt = plainView(poppendorf[[4]])

ui = fluidPage(
  plainViewOutput("plot")
  , textOutput("click_text")
)

server = function(input, output, session) {
  observe({
    click = input$image_click
    
    text = paste("x: ", click$x, ", y: ", click$y)
    text2 = paste("You've clicked ", text)

    output$click_text = renderText({
      text2
    })
  })

  output$plot = renderPlainView(plt)
}

shinyApp(ui, server)
```

**Comment by mosscoder** [comment]
Hi Tim, Thanks for putting in the work. I don't get any output to the ui, or in the console when I wrap input$image_click in print.

**Comment by tim-salabim** [comment]
Do you have a reprex

**Comment by mosscoder** [comment]
The code is identical to your prior post:

```
library(shiny)
library(plainview)

plt = plainView(poppendorf[[4]])

ui = fluidPage(
  plainViewOutput("plot")
  , textOutput("click_text")
)

server = function(input, output, session) {
  observe({
    click = input$image_click
    print(click) #click is null in console
    text = paste("x: ", click$x, ", y: ", click$y)
    text2 = paste("You've clicked ", text)

    output$click_text = renderText({
      text2
    })
  })

  output$plot = renderPlainView(plt)
}

shinyApp(ui, server)
```

**Comment by tim-salabim** [comment]
Assuming you did re-install from GitHub, can you please report your sessionInfo()?

**Comment by mosscoder** [comment]
Apologies, I did get your example to behave as expected after restarting my session. Thank you! I will start a new project branch for my work and see how things go when refactoring in a plainview ecosystem. 

In case you are curious, I've made a [sandbox demo demonstrating the pixel-labeling process in paint2train package.](https://mpgranch.shinyapps.io/paint2train_sandbox/) 

[Repo and long-form docs are here.](https://github.com/mosscoder/paint2train)

I hope to explore the potential for the following features :
- Overlaying multiple images, and manipulating their transparency
- Drawing polygons in a manner similar to leaflet.extras draw tools

**Comment by tim-salabim** [comment]
Nice one, thanks for those links!

Given your intentions, I think we should think about alternative ways to render rasters in their native crs. plainview was and is just a gapfiller for enabling looking at rasters. There was never any intention to provide drawing tools or anything fancy like it. 
If you need this functionality, I firmly believe that a leaflet based solution is much better, though that will need some effort too. 

I just want you to understand that plainview in its current state will not be the tool for your intentions, so that you don't put too much effort into a plainview based approach. That said, maybe plainview is the correct repo for hosting additional and more advanced solutions for working with non geographic raster data that are leaflet based...

**Comment by mosscoder** [comment]
_Given your intentions, I think we should think about alternative ways to render rasters in their native crs. plainview was and is just a gapfiller for enabling looking at rasters. There was never any intention to provide drawing tools or anything fancy like it._

My drive to move away from leaflet is based on the assumption that larger images require more time to render. If a user wanted to work with larger tiles, it might drastically slow down the labeling process. 

I also experimented with project=FALSE for addRasterImage and addRasterRGB early on, but the results were not as expected. I could work on a reprex of this to demonstrate what I mean. 

A lesser issue is that the result of input$myleafletmap_click is in latlon, and must be reprojected. 

**EDIT** ... and for imagery that has no CRS, there isn't a clear path to getting useful click results.
